### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by foxpcteam** [caponica/AmazonProductAdvertisingApi#1]
Hi,
can you please add "how to use" and some code examples?

Thanks

**Comment by caponica** [comment]
It's still in very heavy development (so no BC promises). I'll see if I can put together a quick README some time soon, but it's fairly straightforward:
- create a client using `$apaaClient = ApaaClient::buildFromArray()` (look in the code to see the expected parameters)
- then call methods on the client, e.g. `$itemLookupResponse = $apaaClient->callItemLookupFull($asinsToLookup);` this returns an `ItemLookupResponse` object so you can parse the response and keep your sanity
- if you prefer to get an XML response then use one of the callFooAndReturnXml calls, e.g. `callItemLookupAndReturnXml()`

If you're using Symfony there is also caponica/AmazonProductAdvertisingApiBundle which wraps everything as a service.

I hope that helps!
